# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ByteowlsCapacitorOauth2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteowlsCapacitorOauth2
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'OAuthSwift', '~> 1.3.0'

end
