# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ByteowlsCapacitorOauth2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteowlsCapacitorOauth2

   pod 'Capacitor', '~> 1.0.0-beta.16'
   pod 'OAuthSwift', '~> 1.2.2'

end
